export type LipseysProduct = {
  itemNo: string;
  description1: string;
  description2: string;
  upc: string;
  manufacturerModelNo: string;
  msrp: number;
  model: string;
  caliberGauge: string;
  manufacturer: string;
  type: string;
  action: string;
  barrelLength: string;
  capacity: string;
  finish: string;
  overallLength: string;
  receiver: string | null;
  safety: string | null;
  sights: string;
  stockFrameGrips: string;
  magazine: string;
  weight: string;
  imageName: string;
  chamber: string | null;
  drilledAndTapped: boolean;
  rateOfTwist: string;
  itemType: string;
  additionalFeature1: string;
  additionalFeature2: string;
  additionalFeature3: string;
  shippingWeight: number;
  boundBookManufacturer: string;
  boundBookModel: string;
  boundBookType: string;
  nfaThreadPattern: string | null;
  nfaAttachmentMethod: string | null;
  nfaBaffleType: string | null;
  silencerCanBeDisassembled: boolean;
  silencerConstructionMaterial: string | null;
  nfaDbReduction: string | null;
  silencerOutsideDiameter: string | null;
  nfaForm3Caliber: string | null;
  opticMagnification: string | null;
  maintubeSize: string | null;
  adjustableObjective: boolean;
  objectiveSize: string | null;
  opticAdjustments: string | null;
  illuminatedReticle: boolean;
  reticle: string | null;
  exclusive: boolean;
  quantity: number;
  allocated: boolean;
  onSale: boolean;
  price: number;
  currentPrice: number;
  retailMap: number;
  fflRequired: boolean;
  sotRequired: boolean;
  exclusiveType: string;
  scopeCoverIncluded: boolean;
  special: string | null;
  sightsType: string;
  case: string;
  choke: string | null;
  dbReduction: string | null;
  family: string;
  finishType: string;
  frame: string;
  gripType: string;
  handgunSlideMaterial: string | null;
  countryOfOrigin: string;
  itemLength: string;
  itemWidth: string;
  itemHeight: string;
  packageLength: string;
  packageWidth: string;
  packageHeight: string;
  itemGroup: string;
};